### ISSUE TITLE
Adding a Graphical Coding Environment for the DIY Robot

### ISSUE THREAD

**Issue by cekbote** [eellak/gsoc2019-diyrobot#1]
I really like the work that was done in the project and would like to further contribute to it. I would like to create a graphical coding environment for the robot so that kids, as well as educators, could easily code simple programs. This would help in improving the learning environment for the kids of a slightly younger age. 

I was thinking of creating a GUI using Python and PyQt which would look something like this: https://i.stack.imgur.com/DLHS9.png

**Comment by chronis10** [comment]
Hello, it's a great idea. We are also thinking to program the robot with codeless ways. Also, we are looking to integrate already available solutions like Skratch to the robot.  If you want to further discuss with me your thoughts or to participate as a contributor to the project please don't hesitate to communicate with pm.

**Comment by cekbote** [comment]
Could you please send me your email id where we could further continue this conversation or would you prefer to have it here?

**Comment by chronis10** [comment]
Ok, my email is christos.chronis.dev@gmail.com.

**Comment by cekbote** [comment]
> 
> 
> Ok, my email is [christos.chronis.dev@gmail.com](mailto:christos.chronis.dev@gmail.com).

Dear Christos, 

I had sent you an email regarding the updates to the project. Please check it out as and when time permits.

**Comment by cekbote** [comment]
Hi,
I went through the list of organisations that were selected for GSOC and apparently GFOSS wasn't on that list. Would the list be updated or is it so that GFOSS wasn't selected this year?
